carusel
ReDI-School/F24-Berlin-Web-Circle pull request #168
Opened 2024-10-11 12:36 UTC by 006080

I put SharePopup into the right folder and added a carousel of images.

2024-10-11 13:07 UTC, 006080 commented
Conflict solved

2024-10-12 11:12 UTC, Konzisam commented
there seems to be conflicts

2024-10-12 11:42 UTC, Konzisam commented on src/components/ProductCard/ProductCard.css
>    transform: scale(1.03);
We dont need this unless as it is not in the airbnb,unless  you just like the effect and oyu want to keep it:)

2024-10-12 11:54 UTC, Konzisam requested changes
1. you seemd to have chenged the css file form module.css to .css, do oyu have  reason for that.... because we had agreed to use modular css. 
2. also you remove the router link in the product card unnecesarilly
3. in the products card, the arrow right and left work, but they dont really look like the ones in th airbnb ...(**low priority: I would approve if the above are fixed**)

2024-10-14 07:33 UTC, miklesch commented
Hi, 
beside the last comment of Konzisam I  think it is essential to merge main into your branch as there have been so many changes...

2024-10-15 00:06 UTC, 006080 commented
Hi. team. I am a bit in doubt... I was resolving the conflicts, but after reviewing the project, I noticed that we already have a server-side setup in place. Will be better if we integrate imediately the new destinations JSON file into the server part? 
Or I will first solve a conflict in the current branch?
Let me know if you have any concerns or suggestions! Thanks

2024-10-15 00:31 UTC, Konzisam commented
They are two branches so you need to deal with them independently. 
Conflicts only involve your working branch and main branch and  arise only when something in main is on the same 'line' as something in your branch, git gets confused which one to choose. 
Since the branch with json file isn't merged to main it wont affect anything, it actually won't be a conflict in the first place (even if it was merged) because there is no any other destination json file in main. 
Would suggest just fixing the issues in this specific branch. 
Hope this kind of clears the doubts.

2024-10-15 10:23 UTC, 006080 commented
Thank you for the clarification, but I believe that's quite obvious to
anyone. My question was whether it might be better to wait for the JSON
file branch to be merged. I honestly don’t understand what the issue is
with adding this PR. There’s only one file, with no conflicts. Is it really
that difficult to approve it?

On Tue 15. Oct 2024 at 02:32, Samuel Konzi ***@***.***> wrote:

> They are two branches so you need to deal with them independently.
> Conflicts only involve your working branch and main branch and arise only
> when something in main is on the same 'line' as something in your branch,
> git gets confused which one to choose.
> Since the branch with json file isn't merged to main it wont affect
> anything, it actually won't be a conflict in the first place (even if it
> was merged) because there is no any other destination json file in main.
> Would suggest just fixing the issues in this specific branch.
> Hope this kind of clears the doubts.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/168#issuecomment-2412585369>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25VU37EO2RNUIAUYBB5IR3Z3RPAXAVCNFSM6AAAAABPY2ZAJOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMJSGU4DKMZWHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-15 13:59 UTC, 006080 commented
As I have to move ahead with creating a grid using a Product.js Component I solved conflicts in a current file. I'll wait for approval if it looks good.
Then if it works I will change CSS to modular CSS.

2024-10-16 11:26 UTC, miklesch reviewed
when i start this branch on my machine, i am getting following error: 
[cause]: Error: Cannot find module '@rollup/rollup-win32-x64-msvc'
  Require stack:
  - F:\Coding\Web_Circle\F24-Berlin-Web-Circle\node_modules\rollup\dist\native.js
  
when i update npm, there are still a lot of problems at the productCard component.
please check or leave me a message, if I miss something.

2024-10-16 11:26 UTC, miklesch commented on src/App.jsx
>      </>
The ProductCard component is used twice (also on line 56). Is this on purpose?
The Link here is the old version. it´s currently different on main.

2024-10-16 11:26 UTC, miklesch commented on src/components/ProductCard/ProductCard.jsx
is used twice, also at line 6

2024-10-16 14:24 UTC, 006080 commented
Currently I am working on this branch. Will push the changes very soon.

On Wed 16. Oct 2024 at 13:27, miklesch ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> when i start this branch on my machine, i am getting following error:
> [cause]: Error: Cannot find module ***@***.***/rollup-win32-x64-msvc'
> Require stack:
>
>    -
>    F:\Coding\Web_Circle\F24-Berlin-Web-Circle\node_modules\rollup\dist\native.js
>
> when i update npm, there are still a lot of problems at the productCard
> component.
> please check or leave me a message, if I miss something.
> ------------------------------
>
> In src/App.jsx
> <https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/168#discussion_r1801857947>
> :
>
> >  import PersonProfile from "./components/PersonProfile/PersonProfile";
> +import SearchBar from "./components/SearchBar/SearchBar";
>
> both not needed here
> ------------------------------
>
> In src/App.jsx
> <https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/168#discussion_r1801859371>
> :
>
> > +
> +      <SearchBar></SearchBar>
> +
> +      <PersonProfile
> +        title="Meet your host"
> +        image="https://a0.muscache.com/im/pictures/user/d62627ea-ea22-4cf1-b38a-152f1f86a9ed.jpg"
> +        name="Raus"
> +        role="Superhost"
> +        verified={true}
> +        reviews={74}
> +        rating={4.85}
> +        yearsHosting={1}
> +      />
> +
>
> can be deleted
> ------------------------------
>
> In src/App.jsx
> <https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/168#discussion_r1802906058>
> :
>
> > +      <ProductCard
> +        images={[
> +          "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEzMTA4OTQ5ODA0MDcwMTE4Mw%3D%3D/original/a766e0e9-1e6f-4b88-b8d5-ce12375c6de8.png?im_w=1200&im_q=highq",
> +          "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEzMTA4OTQ5ODA0MDcwMTE4Mw%3D%3D/original/71d534a9-6699-4fe0-ad82-a9aaf0450b56.png?im_w=1200&im_q=highq",
> +          "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTEzMTA4OTQ5ODA0MDcwMTE4Mw%3D%3D/original/3f7a34a4-0052-4d5d-8e81-a75667f48a70.png?im_w=1200&im_q=highq"
> +        ]}
> +        title="Cozy Apartment in City Center"
> +        host="Hosted by Wendy and Elisa"
> +        price="Coming soon"/>
> +
> +      {places.map((place) => {
> +        return (
> +          <Link to={`/rooms/${place.id}`} key={place.id}>
> +            <div>{`${place.id} - ${place.name}`}</div>
> +          </Link>
> +        );
> +      })}
>      </>
>
> The ProductCard component is used twice (also on line 56). Is this on
> purpose?
> The Link here is the old version. it´s currently different on main.
> ------------------------------
>
> In src/components/ProductCard/ProductCard.jsx
> <https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/168#discussion_r1802907750>
> :
>
> >
>  const ProductCard = ({ place }) => {
>
>
> is used twice, also at line 6
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/168#pullrequestreview-2370475046>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25VU36ESNUW2AVVRVNP6DTZ3ZEQ3AVCNFSM6AAAAABPY2ZAJOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZQGQ3TKMBUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-16 15:38 UTC, 006080 commented
![Screenshot from 2024-10-16 17-35-20](https://github.com/user-attachments/assets/674ebcf9-7000-4ca9-a156-5cde15313e7a)

Here is how a Modal looks now.

2024-10-16 16:10 UTC, 006080 commented
![Screenshot from 2024-10-16 18-08-29](https://github.com/user-attachments/assets/19c5e576-4a61-4ecd-9f7c-0b1dd6b78f17)

Here is how a ProductCard looks now :sunglasses:

2024-10-16 16:55 UTC, 006080 commented
![Screenshot from 2024-10-16 18-53-09](https://github.com/user-attachments/assets/8abe9d69-0e32-44ef-b2d7-9883236e4b6c)
SharePopup Modal with overlay.

2024-10-16 16:56 UTC, 006080 commented
I also added dots to the carousel and overlay

2024-10-16 19:44 UTC, Konzisam approved these changes

2024-10-16 19:45 UTC, Konzisam commented
looks good! Kudos Nataliya

2024-10-16 19:47 UTC, merged