Feature/category tabs
ReDI-School/F24-Berlin-Web-Circle pull request #181
Opened 2024-10-17 09:33 UTC by messkalina

I created a scrollable horizontal tabs component. The scroll is executed by clicking the arrows buttons. The left arrow button appears only when we scroll to the right. It is not visible when scrolling left is not possible.

**The component is functional however the hover and active states for tabs items only work for the first 5 tabs.** I dont know how to fix it at this point. I will create a ticket to fix this issue later, once the component is merged.

<img width="1176" alt="Screenshot 2024-10-17 at 11 32 32" src="https://github.com/user-attachments/assets/a57aae37-ea96-4a9e-b898-8bb301ff2805">
<img width="1176" alt="Screenshot 2024-10-17 at 11 32 42" src="https://github.com/user-attachments/assets/f57e5ee1-7ad7-46d2-8292-d0277fecf315">

2024-10-24 09:55 UTC, 006080 commented
Here also a conflict

2024-10-24 14:25 UTC, messkalina commented
> Here also a conflict

The conflict is resolved, ready to merge:)

2024-10-28 08:47 UTC, messkalina commented
I resolved latest merge conflict and the PR is ready to be merged. Pls review, thank you!

2024-10-28 11:02 UTC, 006080 commented
To improve the .category-tabs style, I recommend removing the padding and replacing the border-bottom with a subtle shadow effect for a cleaner look:
.category-tabs {
  display: flex;
  overflow-x: auto;
  white-space: nowrap;
  /* padding: 10px 0; */
  /* border-bottom: 1px solid #ddd; */
  scroll-behavior: smooth;
}
Additionally, since we're standardizing on modular CSS, we should refactor this into a modular component for better reusability and maintenance.

2024-10-28 11:03 UTC, 006080 commented on src/components/CategoryTabs/CategoryTabs.css
> +
To improve the .category-tabs style, I recommend removing the padding and replacing the border-bottom with a subtle shadow effect for a cleaner look:
.category-tabs {
  display: flex;
  overflow-x: auto;
  white-space: nowrap;
  /* padding: 10px 0; */
  /* border-bottom: 1px solid #ddd; */
  scroll-behavior: smooth;
}

2024-10-28 11:05 UTC, 006080 requested changes
To improve the .category-tabs style, I recommend removing the padding and replacing the border-bottom with a subtle shadow effect for a cleaner look:
.category-tabs {
  display: flex;
  overflow-x: auto;
  white-space: nowrap;
  /* padding: 10px 0; */
  /* border-bottom: 1px solid #ddd; */
  scroll-behavior: smooth;
}

2024-10-28 11:05 UTC, 006080 commented
Additionally, since we're standardizing on modular CSS, we should refactor this into a modular component for better reusability and maintenance.

2024-10-29 15:58 UTC, 006080 commented
<div className={styles.categoryTabsContainer}> {/* Modular CSS syntax example */}

2024-10-29 15:59 UTC, 006080 commented
<div className={styles.categoryTabsContainer}> {/* Modular CSS syntax example */}

2024-10-29 16:01 UTC, 006080 commented
div className={styles.categoryTabsContainer}     This is example of the sintax

2024-10-29 17:01 UTC, messkalina commented
> Hey, sorry. Maybe I didn't get a point but I see that CSS file wasn't converted. Styles will never apply in that way:(
> 
> Modular CSS classes are scoped locally to the component to avoid conflicts. After importing the CSS module (e.g., import styles from './Component.module.css'), each CSS class is accessed as a property on the styles object, using styles.className.
> 
> So, category-tabs-container in standard CSS becomes categoryTabsContainer in the CSS module file (Component.module.css).

Ok, I was googling how to tackle this, I dont know how to convert them. I will ask for help on that then. Thank you!

2024-11-01 19:57 UTC, merged